name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build
