name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup node
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build
