name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build
