name: ci

on:
  push:
    branches-ignore:
      - gh-pages
      - "renovate/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup node
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci
      - run: npm run build
